package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


// se cargan los VO y el controlador
import controller.ControladorRequerimientosReto4;
import model.vo.LideresMayorSalario;
import model.vo.LideresProyectosEmblematicos;
import model.vo.MaterialRankeadoImportado;
import view.VistaRequerimientosReto4;

// arreglos y colecciones
import java.sql.SQLException;
import java.util.ArrayList;
/**
 *
 * @author messe
 */
public class VistaConstructoraGui extends javax.swing.JFrame {

    /**
     * Creates new form VistaConstructoraGui
     */
    public VistaConstructoraGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneReto5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonLideres = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLideres = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButtonEmblematicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEmblematicos = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButtonImportado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextMaterial = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MisionTic 2022 Miguel Martinez G72R5");

        jPanel1.setToolTipText("Mision Tic Miguel Martinez G72R5");

        jTabbedPaneReto5.setBackground(new java.awt.Color(204, 204, 204));

        jButtonLideres.setText("Cargar");
        jButtonLideres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLideresMouseClicked(evt);
            }
        });
        jButtonLideres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLideresActionPerformed(evt);
            }
        });

        jTextAreaLideres.setEditable(false);
        jTextAreaLideres.setColumns(20);
        jTextAreaLideres.setRows(5);
        jScrollPane3.setViewportView(jTextAreaLideres);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLideres)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLideres)
                .addContainerGap())
        );

        jButtonLideres.getAccessibleContext().setAccessibleName("cargarLideres");

        jTabbedPaneReto5.addTab("Mejores Líderes", jPanel2);

        jButtonEmblematicos.setText("Cargar");
        jButtonEmblematicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEmblematicosMouseClicked(evt);
            }
        });
        jButtonEmblematicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmblematicosActionPerformed(evt);
            }
        });

        jTextAreaEmblematicos.setEditable(false);
        jTextAreaEmblematicos.setColumns(20);
        jTextAreaEmblematicos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEmblematicos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jButtonEmblematicos)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmblematicos)
                .addContainerGap())
        );

        jButtonEmblematicos.getAccessibleContext().setAccessibleName("cargarProyectos");

        jTabbedPaneReto5.addTab("Proyectos Emblematicos", jPanel4);

        jButtonImportado.setText("Cargar");
        jButtonImportado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportadoActionPerformed(evt);
            }
        });

        jTextMaterial.setEditable(false);
        jTextMaterial.setColumns(20);
        jTextMaterial.setRows(5);
        jScrollPane2.setViewportView(jTextMaterial);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jButtonImportado)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImportado)
                .addContainerGap())
        );

        jButtonImportado.getAccessibleContext().setAccessibleName("cargarMaterial");

        jTabbedPaneReto5.addTab("Material Importado", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneReto5, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneReto5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLideresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLideresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLideresActionPerformed

    private void jButtonLideresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLideresMouseClicked
        // TODO add your handling code here:
        jTextAreaLideres.setText(VistaRequerimientosReto4.requerimiento1());
    }//GEN-LAST:event_jButtonLideresMouseClicked

    private void jButtonImportadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportadoActionPerformed
        // TODO add your handling code here:
        jTextMaterial.setText(VistaRequerimientosReto4.requerimiento4());
    }//GEN-LAST:event_jButtonImportadoActionPerformed

    private void jButtonEmblematicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEmblematicosMouseClicked
        // TODO add your handling code here:
        jTextAreaEmblematicos.setText(VistaRequerimientosReto4.requerimiento3());
    }//GEN-LAST:event_jButtonEmblematicosMouseClicked

    private void jButtonEmblematicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmblematicosActionPerformed
        // TODO add your handling code here:
        jTextAreaEmblematicos.setText(VistaRequerimientosReto4.requerimiento3());
    }//GEN-LAST:event_jButtonEmblematicosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmblematicos;
    private javax.swing.JButton jButtonImportado;
    private javax.swing.JButton jButtonLideres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneReto5;
    public javax.swing.JTextArea jTextAreaEmblematicos;
    private javax.swing.JTextArea jTextAreaLideres;
    public javax.swing.JTextArea jTextMaterial;
    // End of variables declaration//GEN-END:variables
}
