/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practinotas.resources;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel A Martinez
 */
public class Presentacion extends javax.swing.JFrame {

    private Object areaDeTexto;

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        ABRIR = new javax.swing.JMenuItem();
        GUARDAR = new javax.swing.JMenuItem();
        CERRAR = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ACERCA = new javax.swing.JMenuItem();

        file.setDoubleBuffered(true);
        file.setFileSystemView(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practi Note");

        CampoTexto.setBackground(new java.awt.Color(0, 0, 51));
        CampoTexto.setColumns(60);
        CampoTexto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CampoTexto.setForeground(new java.awt.Color(204, 204, 255));
        CampoTexto.setRows(5);
        jScrollPane1.setViewportView(CampoTexto);
        CampoTexto.getAccessibleContext().setAccessibleName("CampoTexto");

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jMenu1.add(Nuevo);

        ABRIR.setText("Abrir");
        ABRIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABRE(evt);
            }
        });
        ABRIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABRIRActionPerformed(evt);
            }
        });
        jMenu1.add(ABRIR);

        GUARDAR.setText("Guardar");
        GUARDAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUARDARMouseClicked(evt);
            }
        });
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        jMenu1.add(GUARDAR);

        CERRAR.setText("Cerrar");
        CERRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CERRARMouseClicked(evt);
            }
        });
        CERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CERRARActionPerformed(evt);
            }
        });
        jMenu1.add(CERRAR);
        jMenu1.add(jSeparator1);

        ACERCA.setText("Acerca de...");
        ACERCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACERCAActionPerformed(evt);
            }
        });
        jMenu1.add(ACERCA);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUARDARMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_GUARDARMouseClicked

    }// GEN-LAST:event_GUARDARMouseClicked

    private void CERRARMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_CERRARMouseClicked

    }// GEN-LAST:event_CERRARMouseClicked

    private void ABRE(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ABRE

    }// GEN-LAST:event_ABRE

    private void ABRIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ABRIRActionPerformed
        String aux = "";
        String texto = "";
        try {
            /** llamamos el metodo que permite cargar la ventana */
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(null);
            /** abrimos el archivo seleccionado */
            File abre = file.getSelectedFile();

            /**
             * recorremos el archivo, lo leemos para plasmarlo en el area de texto
             */
            if (abre != null) {
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                while ((aux = lee.readLine()) != null) {
                    texto = texto + aux + "\n";
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!",
                    JOptionPane.WARNING_MESSAGE);
        }
        CampoTexto.setText(texto);
        return;
    }// GEN-LAST:event_ABRIRActionPerformed

    private void CERRARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CERRARActionPerformed

        System.exit(0);
    }// GEN-LAST:event_CERRARActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GUARDARActionPerformed

        try {
            String nombre = "";

            JFileChooser file = new JFileChooser();
            file.setDialogTitle("Guardar Archivo de Texto");
            file.showSaveDialog(this);
            File guarda = file.getSelectedFile();

            if (guarda != null) {
                /*
                 * guardamos el archivo y le damos el formato directamente, si queremos que se
                 * guarde en formato doc lo definimos como .doc
                 */
                FileWriter save = new FileWriter(guarda);
                save.write(Presentacion.CampoTexto.getText());
                save.close();
                JOptionPane.showMessageDialog(null, "Archivo Guardado", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!",
                    JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_GUARDARActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NuevoActionPerformed

        CampoTexto.setText("");

    }// GEN-LAST:event_NuevoActionPerformed

    private void ACERCAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ACERCAActionPerformed

        JOptionPane.showMessageDialog(null,
                "Practi Note 2.0\nMiguel A Martinez\nJava Swing Editor de Texto\nMINTIC UTP", "Acerca De...",
                JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_ACERCAActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ABRIR;
    private javax.swing.JMenuItem ACERCA;
    private javax.swing.JMenuItem CERRAR;
    public static javax.swing.JTextArea CampoTexto;
    private javax.swing.JMenuItem GUARDAR;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JFileChooser file;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
